/*
 * @Author: Azhou
 * @Date: 2021-05-11 23:09:33
 * @LastEditors: Azhou
 * @LastEditTime: 2021-06-15 15:23:36
 */
export const UPDATE_USER_DETAIL = 'UPDATE_USER_DETAIL'
export const UPDATE_USER_PROJECTS = 'UPDATE_USER_PROJECTS'
export const UPDATE_USER_LOGIN = 'UPDATE_USER_LOGIN'

export const UPDATE_PROJECT_DETAIL = 'UPDATE_PROJECT_DETAIL'
export const UPDATE_PROJECT_HITS = 'UPDATE_PROJECT_HITS'
export const UPDATE_PROJECT_MODELS = 'UPDATE_PROJECT_MODELS'
export const UPDATE_CURRENT_HITS = 'UPDATE_CURRENT_HITS'
export const UPDATE_CURRENT_HIT_INDEX = 'UPDATE_CURRENT_HIT_INDEX'
export const UPDATE_BOUNDING_BOX_MAP = 'UPDATE_BOUNDING_BOX_MAP'

export const UPDATE_CURRENT_CANVAS = 'UPDATE_CURRENT_CANVAS'
export const UPDATE_CURRENT_CLASSIFY_INFO = 'UPDATE_CURRENT_CLASSIFY_INFO'
export const UPDATE_CURRENT_ENTITY = 'UPDATE_CURRENT_ENTITY'
export const UPDATE_CURRENT_SHAPE = 'UPDATE_CURRENT_SHAPE'
export const UPDATE_CURRENT_TRAPATHWAY = 'UPDATE_CURRENT_TRAPATHWAY'
export const UPDATE_CURRENT_INTEPATHWAY = 'UPDATE_CURRENT_INTEPATHWAY'
export const UPDATE_CURRENT_CONTROL_TYPE = 'UPDATE_CURRENT_CONTROL_TYPE'
export const UPDATE_CURRENT_IMAGE_SIZE = 'UPDATE_CURRENT_IMAGE_SIZE'
export const UPDATE_SEGPOSITIVE = 'UPDATE_SEGPOSITIVE'
export const UPDATE_THRESHOLD = 'UPDATE_THRESHOLD'
export const UPDATE_CANNYTHRESHOLD = 'UPDATE_CANNYTHRESHOLD'
export const UPDATE_WS_INSTANCE = 'UPDATE_WS_INSTANCE'
export const UPDATE_CURRENT_MODEL = 'UPDATE_CURRENT_MODEL'
