/*
 * @Author: Azhou
 * @Date: 2021-05-11 23:09:33
 * @LastEditors: Azhou
 * @LastEditTime: 2021-06-15 15:23:36
 */
export const UPDATE_USER_DETAIL = 'UPDATE_USER_DETAIL'
export const UPDATE_USER_PROJECTS = 'UPDATE_USER_PROJECTS'
export const UPDATE_CURRENT_USER_PROJECTS = 'UPDATE_CURRENT_USER_PROJECTS'
export const UPDATE_CURRENT_USER_PROJECTS_LENGTH = 'UPDATE_CURRENT_USER_PROJECTS_LENGTH'
export const UPDATE_CURRENT_USER_GROUPS = 'UPDATE_CURRENT_USER_GROUPS'
export const UPDATE_CURRENT_USER_GROUPS_LENGTH = 'UPDATE_CURRENT_USER_GROUPS_LENGTH'
export const UPDATE_USER_LOGIN = 'UPDATE_USER_LOGIN'

export const UPDATE_PROJECT_DETAIL = 'UPDATE_PROJECT_DETAIL'
export const UPDATE_PROJECT_HITS = 'UPDATE_PROJECT_HITS'
export const UPDATE_PROJECT_PATHOIMGINFO = 'UPDATE_PROJECT_PATHOIMGINFO'
export const UPDATE_CURRENT_HITS = 'UPDATE_CURRENT_HITS'
export const UPDATE_CURRENT_HIT_INDEX = 'UPDATE_CURRENT_HIT_INDEX'
export const UPDATE_BOUNDING_BOX_MAP = 'UPDATE_BOUNDING_BOX_MAP'

export const UPDATE_CURRENT_CANVAS = 'UPDATE_CURRENT_CANVAS'
export const UPDATE_CURRENT_SHAPE = 'UPDATE_CURRENT_SHAPE'
export const UPDATE_CURRENT_CONTROL_TYPE = 'UPDATE_CURRENT_CONTROL_TYPE'
export const UPDATE_CURRENT_IMAGE_SIZE = 'UPDATE_CURRENT_IMAGE_SIZE'
export const UPDATE_CURRENT_COLOR = 'UPDATE_CURRENT_COLOR'
export const UPDATE_CURRENT_ACTIVE_OBJ = 'UPDATE_CURRENT_ACTIVE_OBJ'
export const UPDATE_CURRENT_VIEWER = 'UPDATE_CURRENT_VIEWER'
export const UPDATE_CURRENT_GROUP = 'UPDATE_CURRENT_GROUP'
export const UPDATE_CURRENT_PROJECT_GROUPS = 'UPDATE_CURRENT_PROJECT_GROUPS'
export const UPDATE_CURRENT_GROUP_IMAGES = 'UPDATE_CURRENT_GROUP_IMAGES'
export const UPDATE_CURRENT_IMAGE = 'UPDATE_CURRENT_IMAGE'
export const UPDATE_CURRENT_GROUP_LENGTH = 'UPDATE_CURRENT_GROUP_LENGTH'
export const UPDATE_CURRENT_QUESTION = 'UPDATE_CURRENT_QUESTION'
export const UPDATE_DEFAULT_GROUP_INFO = 'UPDATE_DEFAULT_GROUP_INFO'
export const UPDATE_CURRENT_LLM_TASK_TYPE = 'UPDATE_CURRENT_LLM_TASK_TYPE'
export const UPDATE_STROKEWIDTH = 'UPDATE_STROKEWIDTH'
export const UPDATE_CIRCLERADIUS = 'UPDATE_CIRCLERADIUS'
export const UPDATE_ISMUTITAG = 'UPDATE_ISMUTITAG'
export const UPDATE_WS_INSTANCE = 'UPDATE_WS_INSTANCE'
export const UPDATE_PATHOVIEWSIZE = 'UPDATE_PATHOVIEWSIZE'

export const CLEAR_PROJECT_STATE = 'CLEAR_PROJECT_STATE'
export const UPDATE_LAUNCH_REF_PROCESS = 'UPDATE_LAUNCH_REF_PROCESS'
